# Generated by Django 3.1.7 on 2022-01-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='AttemptId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RestApi.attempts'),
        ),
    ]
