# Generated by Django 3.1.7 on 2022-01-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0003_remove_choices_istrue'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='other',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choose',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.BooleanField(default=False),
        ),
    ]
