# Generated by Django 3.1.7 on 2022-01-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0006_auto_20220107_1644'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together={('question', 'AttemptId')},
        ),
    ]
