# Generated by Django 3.1.7 on 2022-01-07 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0007_auto_20220108_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='AttemptId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='RestApi.attempts'),
        ),
    ]
